import type { Metadata } from "next";
import "./globals.css";
import { Outfit, Oxanium } from "next/font/google";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
import Navbar from "@/components/shared/navbar";

const oxaniumHeading = Oxanium({subsets:['latin'],variable:'--font-heading'});

const outfit = Outfit({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "prisma press frontend",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "font-sans", outfit.variable, oxaniumHeading.variable)}
    >
      <body > 
        <Navbar></Navbar>
        {children}
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );        
}
   